http {
    server {
        listen 55;
        server_name l3.onchaincoin.io;
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 445 ssl;
        server_name l3.onchaincoin.io;
        ssl_certificate /etc/letsencrypt/live/l3.onchaincoin.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/l3.onchaincoin.io/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
        location / {
            proxy_pass http://app:2310;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
