http {
    server {
        listen 80;
        server_name l3.onchaincoin.io;
        location / {
            return 301 https://$host$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name l3.onchaincoin.io;
        ssl_certificate /etc/letsencrypt/live/l3.onchaincoin.io/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/l3.onchaincoin.io/privkey.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://app:2310;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}